# Generated by Django 5.2.10 on 2026-01-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_schoolclass_attendance_student_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('L', 'Late'), ('A', 'Absent'), ('SL', 'Short Leave')], max_length=2),
        ),
    ]
