# Generated by Django 5.2.10 on 2026-01-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_diaryentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
