# Generated by Django 5.2.10 on 2026-01-21 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_dossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCurricularItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
                ('is_attendance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCurricularMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.extracurricularitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_marks', to='accounts.student')),
            ],
        ),
    ]
