# Generated by Django 5.2.10 on 2026-01-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_extracurricularitem_extracurricularmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularmarks',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.term'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='extracurricularmarks',
            unique_together={('student', 'item', 'term')},
        ),
    ]
