# Generated by Django 5.2.10 on 2026-01-22 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_extracurricularmarks_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricularitem',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.schoolclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracurricularitem',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.term'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='extracurricularitem',
            unique_together={('name', 'school_class', 'term')},
        ),
    ]
