# Generated by Django 5.2.10 on 2026-01-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_extracurricularitem_school_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracurricularitem',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='extracurricularitem',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracurricularitem',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricularitem',
            name='total_marks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='extracurricularmarks',
            name='obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricularmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
