# Generated by Django 5.2.10 on 2026-01-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
