# Generated by Django 5.2.10 on 2026-01-26 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
