# Generated by Django 5.2.10 on 2026-01-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_teachersalary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersalary',
            old_name='month',
            new_name='date',
        ),
    ]
