# Generated by Django 5.2.10 on 2026-01-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_rename_month_teachersalary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalary',
            name='total_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
