# Generated by Django 5.2.10 on 2026-01-26 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_teachersalary_total_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100)),
                ('value', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.term')),
            ],
            options={
                'unique_together': {('student', 'term', 'attribute')},
            },
        ),
    ]
