# Generated by Django 5.2.10 on 2026-01-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_personalattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='personalattribute',
            name='level',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory')], max_length=20, null=True),
        ),
    ]
