# Generated by Django 5.2.10 on 2026-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_personalattribute_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='annual_sub_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='annual_sub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
