# Generated by Django 5.2.10 on 2026-01-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_student_annual_sub_paid_alter_student_annual_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='annual_sub',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='annual_sub_paid',
            field=models.IntegerField(default=0),
        ),
    ]
